### ISSUE TITLE
Scaffold (0.0.10) not working with ember-cli 0.2.3

### ISSUE THREAD

**Issue by emilkarl** [marcioj/ember-cli-scaffold#9]
I setup a new ember-cli project and added ember-cli-scaffold like this `npm install --save-dev ember-cli-scaffold`

Doing `ember generate scaffold farmer name:string location:string`generates the following error:

```
$ ember generate scaffold farmer name:string location:string                                                                                      [14:51:32]
version: 0.2.3
undefined is not a function
TypeError: undefined is not a function
    at Class.module.exports.Task.extend.run (/Sites/myapp/frontend/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:30:24)
    at Class.module.exports.Command.extend.run (/Sites/myapp/frontend/node_modules/ember-cli/lib/commands/generate.js:79:17)
    at Class.<anonymous> (/Sites/myapp/frontend/node_modules/ember-cli/lib/models/command.js:136:17)
    at lib$rsvp$$internal$$tryCatch (/Sites/myapp/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Sites/myapp/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Sites/myapp/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Sites/myapp/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by marcioj** [comment]
Hi @emilkarl, thanks for report this bug!
I just released a new version which should fix this issue, can you try it out?

Runs `npm install --save-dev ember-cli-scaffold@0.0.11`

And then `ember generate scaffold farmer name:string location:string` should work

**Comment by emilkarl** [comment]
Worked like a charm. Thanks!
